/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.event.KeyEvent;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import modelo.AlunoVO;
import servicos.AlunoServicos;

/**
 *
 * @author 182210104
 */
public class GUICadAluno extends javax.swing.JInternalFrame {

    /**
     * Creates new form GUICadAluno
     */
    public GUICadAluno() {
        initComponents();
        
        jtfNome.setDocument(new Limitador(30, Limitador.TipoEntrada.nome));
        jtfEndereco.setDocument(new Limitador(40, Limitador.TipoEntrada.endereco));
        jtfCidade.setDocument(new Limitador(15, Limitador.TipoEntrada.cidade));
        jtaObservacao.setDocument(new Limitador(130, Limitador.TipoEntrada.observacao));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jcbEstado = new javax.swing.JComboBox<>();
        jtfNome = new javax.swing.JTextField();
        jtfEndereco = new javax.swing.JTextField();
        jtfCidade = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jcbTDS = new javax.swing.JCheckBox();
        jcbTI = new javax.swing.JCheckBox();
        jcbTR = new javax.swing.JCheckBox();
        jLayeredPane2 = new javax.swing.JLayeredPane();
        jLabel6 = new javax.swing.JLabel();
        jbtnCadastrar = new javax.swing.JButton();
        jbtnCancelar = new javax.swing.JButton();
        jbtnSair = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtaObservacao = new javax.swing.JTextArea();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Cadastro");

        jLabel1.setText("Nome:");

        jLabel2.setText("Endereço:");

        jLabel3.setText("Cidade:");

        jLabel4.setText("Estado:");

        jcbEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "AC", "AL", "AP", "AM", "BA", "CE", "ES", "GO", "MA", "MT", "MS", "MG", "PA", "PB", "PR", "PE", "PI", "RJ", "RN", "RS", "RO", "RR", "SC", "SP", "SE", "TO", "DF" }));
        jcbEstado.setToolTipText("AC"
            + "AL"
            + "AP"
            + "AM"
            + "BA"
            + "CE"
            + "ES"
            + "GO"
            + "MA"
            + "MT"
            + "MS"
            + "MG"
            + "PA"
            + "PB"
            + "PR"
            + "PE"
            + "PI"
            + "RJ"
            + "RN"
            + "RS"
            + "RO"
            + "RR"
            + "SC"
            + "SP"
            + "SE"
            + "TO"
            + "DF");
        jcbEstado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbEstadoActionPerformed(evt);
            }
        });

        jLabel5.setText("Cursos Matriculados:");

        jcbTDS.setText("Tec. Desenvolvimento de sistemas");
        jcbTDS.setToolTipText("Técnico em desenvolvimento de sistemas");

        jcbTI.setText("Técnico em informática");
        jcbTI.setToolTipText("Técnico em informática");

        jcbTR.setText("Técnico em redes");
        jcbTR.setToolTipText("Técnico em redes");

        jLayeredPane1.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jLabel2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jLabel3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jLabel4, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jcbEstado, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jtfNome, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jtfEndereco, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jtfCidade, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jLabel5, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jcbTDS, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jcbTI, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jcbTR, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jLayeredPane1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jtfNome, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jLayeredPane1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jtfEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jtfCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jLayeredPane1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addComponent(jcbTDS)))
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jLayeredPane1Layout.createSequentialGroup()
                        .addGap(97, 97, 97)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jcbEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jLayeredPane1Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(jcbTI)
                        .addGap(35, 35, 35)
                        .addComponent(jcbTR)))
                .addContainerGap(91, Short.MAX_VALUE))
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jtfNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jtfEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jcbEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jcbTDS)
                    .addComponent(jcbTI)
                    .addComponent(jcbTR))
                .addContainerGap(123, Short.MAX_VALUE))
        );

        jLabel6.setText("Observação:");

        jbtnCadastrar.setText("Cadastrar");
        jbtnCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnCadastrarActionPerformed(evt);
            }
        });
        jbtnCadastrar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jbtnCadastrarKeyPressed(evt);
            }
        });

        jbtnCancelar.setText("Cancelar");
        jbtnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnCancelarActionPerformed(evt);
            }
        });

        jbtnSair.setText("Sair");
        jbtnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnSairActionPerformed(evt);
            }
        });

        jtaObservacao.setColumns(20);
        jtaObservacao.setRows(5);
        jScrollPane1.setViewportView(jtaObservacao);

        jLayeredPane2.setLayer(jLabel6, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(jbtnCadastrar, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(jbtnCancelar, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(jbtnSair, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(jScrollPane1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane2Layout = new javax.swing.GroupLayout(jLayeredPane2);
        jLayeredPane2.setLayout(jLayeredPane2Layout);
        jLayeredPane2Layout.setHorizontalGroup(
            jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane2Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jLayeredPane2Layout.createSequentialGroup()
                        .addComponent(jbtnCadastrar)
                        .addGap(87, 87, 87)
                        .addComponent(jbtnCancelar)
                        .addGap(85, 85, 85)
                        .addComponent(jbtnSair))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 505, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jLayeredPane2Layout.setVerticalGroup(
            jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane2Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtnCadastrar)
                    .addComponent(jbtnCancelar)
                    .addComponent(jbtnSair))
                .addContainerGap(84, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1)
            .addComponent(jLayeredPane2)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLayeredPane2))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

       private void cadastrar(){
           
           try{      
        AlunoVO aVO = new AlunoVO();
        ArrayList curso = new ArrayList();
        ArrayList estado = new ArrayList();
        
        aVO.setNome(jtfNome.getText());
        aVO.setEndereco(jtfEndereco.getText());
        aVO.setCidade(jtfCidade.getText());
        aVO.setObservacao(jtaObservacao.getText());
        
        
        if(jcbTDS.isSelected()){
            curso.add(jcbTDS.getText());
        }
        if(jcbTI.isSelected()){
            curso.add(jcbTI.getText());
        }
        if(jcbTR.isSelected()){
            curso.add(jcbTR.getText());
        }
        aVO.setCursos(curso);
        
        if(jcbEstado.getSelectedItem().equals("AC")){
            estado.add("AC");
        }
        if(jcbEstado.getSelectedItem().equals("AL")){
            estado.add("AL");
        }
        if(jcbEstado.getSelectedItem().equals("AP")){
            estado.add("AP");
        }
        if(jcbEstado.getSelectedItem().equals("AM")){
            estado.add("AM");
        }
        if(jcbEstado.getSelectedItem().equals("BA")){
            estado.add("BA");
        }
        if(jcbEstado.getSelectedItem().equals("CE")){
            estado.add("CE");
        }
        if(jcbEstado.getSelectedItem().equals("ES")){
            estado.add("ES");
        }
        if(jcbEstado.getSelectedItem().equals("GO")){
            estado.add("GO");
        }
        if(jcbEstado.getSelectedItem().equals("MA")){
            estado.add("MA");
        }
        if(jcbEstado.getSelectedItem().equals("MT")){
            estado.add("MT");
        }
        if(jcbEstado.getSelectedItem().equals("MS")){
            estado.add("MS");
        }
        if(jcbEstado.getSelectedItem().equals("MG")){
            estado.add("MG");
        }
        if(jcbEstado.getSelectedItem().equals("PA")){
            estado.add("PA");
        }
        if(jcbEstado.getSelectedItem().equals("PB")){
            estado.add("PB");
        }
        if(jcbEstado.getSelectedItem().equals("PR")){
            estado.add("PR");
        }
        if(jcbEstado.getSelectedItem().equals("PE")){
            estado.add("PE");
        }
        if(jcbEstado.getSelectedItem().equals("PI")){
            estado.add("PI");
        }
        if(jcbEstado.getSelectedItem().equals("RJ")){
            estado.add("RJ");
        }
        if(jcbEstado.getSelectedItem().equals("RN")){
            estado.add("RN");
        }
        if(jcbEstado.getSelectedItem().equals("RS")){
            estado.add("RS");
        }
        if(jcbEstado.getSelectedItem().equals("RO")){
            estado.add("RO");
        }
        if(jcbEstado.getSelectedItem().equals("RR")){
            estado.add("RR");
        }
        if(jcbEstado.getSelectedItem().equals("SC")){
            estado.add("SC");
        }
        if(jcbEstado.getSelectedItem().equals("SP")){
            estado.add("SP");
        }
        if(jcbEstado.getSelectedItem().equals("SE")){
            estado.add("SE");
        }
        if(jcbEstado.getSelectedItem().equals("TO")){
            estado.add("TO");
        }
        if(jcbEstado.getSelectedItem().equals("DF")){
            estado.add("DF");
        }
        
        aVO.setEstado(estado);
        AlunoServicos as = servicos.ServicosFactory.getAlunoServicos();
        
        as.cadastrarAluno(aVO);
        
        JOptionPane.showMessageDialog(
        rootPane,
                "CADASTRO REALIZADO COM SUCESSO"+
                "\nDados cadastrados!!"+ aVO.toString(),
                "\nSucesso",
                JOptionPane.PLAIN_MESSAGE
        );
        }catch(Exception e){
            JOptionPane.showMessageDialog(
                    rootPane,
                    "Erro! " + e.getMessage(),
                    "Erro",
                    JOptionPane.ERROR_MESSAGE);
       }
       }
            private void limpar(){
                jtfNome.setText(null);
                jtfEndereco.setText(null);
                jtfCidade.setText(null);
                jtaObservacao.setText(null);
                jcbEstado.setSelectedItem("AC");
                jcbTDS.setSelected(false);
                jcbTI.setSelected(false);
                jcbTR.setSelected(false);
        }
    private void jbtnCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnCadastrarActionPerformed
        // TODO add your handling code here:
        cadastrar();
        limpar();
    }//GEN-LAST:event_jbtnCadastrarActionPerformed

    private void jbtnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnCancelarActionPerformed
        // TODO add your handling code here:
        limpar();
    }//GEN-LAST:event_jbtnCancelarActionPerformed

    private void jbtnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnSairActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jbtnSairActionPerformed

    private void jcbEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbEstadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcbEstadoActionPerformed

    private void jbtnCadastrarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jbtnCadastrarKeyPressed
             if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            cadastrar();
           }
    }//GEN-LAST:event_jbtnCadastrarKeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JLayeredPane jLayeredPane2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbtnCadastrar;
    private javax.swing.JButton jbtnCancelar;
    private javax.swing.JButton jbtnSair;
    private javax.swing.JComboBox<String> jcbEstado;
    private javax.swing.JCheckBox jcbTDS;
    private javax.swing.JCheckBox jcbTI;
    private javax.swing.JCheckBox jcbTR;
    private javax.swing.JTextArea jtaObservacao;
    private javax.swing.JTextField jtfCidade;
    private javax.swing.JTextField jtfEndereco;
    private javax.swing.JTextField jtfNome;
    // End of variables declaration//GEN-END:variables
}
